StoreOnline/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf.urls.static import static

from StoreOnline import views

urlpatterns = [
    path('usuarios/login',views.login_view, name='login'),
    path('usuarios/logout',views.logout_view, name='logout'),
    path('usuarios/register',views.register, name='register'),
    path('admin/', admin.site.urls),
    path('productos/', include('products.urls', namespace='products')),
    path('carrito/', include('carts.urls',namespace='carts')),
    path('ordenes/', include('orders.urls',namespace='orders')),
    path('direcciones/', include('shipping_address.urls', namespace='shipping_address')),
    path('codigos/', include('promo_code.urls', namespace='codes')),
    path('pagos/',include('billing_profiles.urls',namespace='billing_profiles')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

billing_profiles/urls.py
from django.urls import path
from billing_profiles import views

app_name = 'billing_profiles'

urlpatterns = [
    path('nuevo', views.create, name='create'),
]

carts/urls.py
from django.urls import path
from carts import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove'),
]

orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('direccion', views.address, name='address'),
    path('seleccionar/direccion', views.select_address, name='select_address'),
    path('establecer/direccion/<int:pk>', views.check_address, name='check_address'),
    path('confirmacion', views.confirm, name='confirm'),
    path('cancelar', views.cancel, name='cancel'),
    path('completar', views.complete, name='complete'),
    path('completados', views.OrderListView.as_view(), name='completed'),
]

promo_code/urls.py
from django.urls import path

from promo_code import views

app_name = 'promo_code'

urlpatterns = [
    path('validar', views.validate, name='validar'),
]

orders/models.py
from operator import truediv
from django.db import models
from carts.models import Cart
import promo_code
import shipping_address
from users.models import User
import uuid
from django.db.models.signals import pre_save
from random import choices
from shipping_address.models import ShippingAddress
from orders.common import OrderStatus
from orders.common import choices
from promo_code.models import PromoCode
import decimal

class Order(models.Model):
    order_id = models.CharField(max_length=100,null=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    status = models.CharField(max_length=50, choices=choices, default=OrderStatus.CREATED)
    shipping_total = models.DecimalField(default=5, max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    created_at = models.DateField(auto_now_add=True)
    shipping_address = models.ForeignKey(ShippingAddress, null=True, blank=True, on_delete=models.CASCADE)
    promo_code = models.OneToOneField(PromoCode, null=True, blank=True, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.order_id
    
    def apply_promo_code(self, promo_code):
        if self.promo_code is None:
            self.promo_code = promo_code
            self.save()
            self.update_total()
            promo_code.use()

    def get_or_set_shipping_address(self):
        if self.shipping_address:
            return self.shipping_address
        shipping_address = self.user.shipping_address
        if shipping_address:
            self.update_shipping_address(shipping_address)
        return shipping_address
    
    def update_shipping_address(self, shipping_address):
        self.shipping_address = shipping_address
        self.save()

    def cancel(self):
        self.status = OrderStatus.CANCELED
        self.save()
    
    def complete(self):
        self.status = OrderStatus.COMPLETED
        self.save()
        
    def update_total(self):
        self.total = self.get_total()
        self.save()
    
    def get_discount(self):
        if self.promo_code:
            return self.promo_code.discount
        return 0

    def get_total(self):
        return self.cart.total + self.shipping_total - decimal.Decimal(self.get_discount())

def set_order_id(sender, instance, *args, **kwargs):
    if not instance.order_id:
        instance.order_id = str(uuid.uuid4())

def set_total(sender, instance, *args, **kwargs):
    instance.total = instance.get_total()

pre_save.connect(set_order_id, sender=Order)
pre_save.connect(set_total, sender=Order)

orders/views.py
from ast import arg
from urllib import request
from django import conf
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.query import EmptyQuerySet
from django.views import generic

from carts.utils import get_or_create_cart
from orders.models import Order
from orders.utils import get_or_create_order
from orders.utils import breadcrumb
from shipping_address.models import ShippingAddress
from carts.utils import destroy_cart
from orders.utils import destroy_order
from orders.mails import Mail
from orders.decorator import validate_car_and_order

import shipping_address
import re
import threading

@login_required(login_url='login')
@validate_car_and_order
def order(request,cart,order):
    return render(request, 'order.html', {
        'cart': cart,
        'order': order,
        'breadcrumb': breadcrumb,
        })
@login_required(login_url='login')
@validate_car_and_order
def address(request,cart,order):
    shipping_address = order.get_or_set_shipping_address()
    can_choose_address = request.user.has_shipping_addresses()
    return render(request, 'address.html', context={
        'cart':cart,
        'order':order,
        'shipping_address':shipping_address,
        'can_choose_address':can_choose_address,
        'breadcrumb':breadcrumb(address=True),
    })
@login_required(login_url='login')
def select_address(request):
    shipping_addresses = request.user.addresses
    return render(request, 'select_address.html', {
        'breadcrumb':breadcrumb(address=True),
        'shipping_addresses':shipping_addresses,
    })

@login_required(login_url='login')
@validate_car_and_order
def check_address(request,cart,order,pk):
    shipping_address =get_object_or_404(ShippingAddress, pk=pk)

    if request.user.id != shipping_address.user.id:
        return redirect('carts:cart')

    order.update_shipping_address(shipping_address)
    return redirect('orders:address')

@login_required(login_url='login')
@validate_car_and_order
def confirm(request,cart,order):
    shipping_address = order.shipping_address
    if shipping_address is None:
        return redirect('orders:address')
    return render(request, 'confirm.html', {
    'cart':cart,
    'order':order,
    'shipping_address':shipping_address,
    'breadcrumb':breadcrumb(address=True, confirmation=True),
    })

@login_required(login_url='login')
@validate_car_and_order
def cancel(request,cart,order):
    if request.user.id != order.user_id:
        return redirect('carts:cart')
    order.cancel()
    destroy_order(request)
    destroy_cart(request)
    
    messages.error(request, 'Orden Cancelada')
    return redirect('products:index')

@login_required(login_url='login')
@validate_car_and_order
def complete(request,cart,order):
    if request.user.id != order.user_id:
        return redirect('carts:cart')
    order.complete()
    
    thread = threading.Thread(target=Mail.send_complete_order, args=(
        order, request.user
    ))
    thread.start()

    destroy_order(request)
    destroy_cart(request)

    messages.success(request, 'Compra Exitosa')
    return redirect('products:index')

class OrderListView(LoginRequiredMixin, generic.ListView):
    login_url = 'login'
    template_name = 'orders.html'

    def get_queryset(self):
        return self.request.user.orders_completed()

orders/templates/address.html
{% extends "base/base.html" %}
{% block breadcrumb %}
    {% include "snippets/breadcrumb.html" %}
{% endblock breadcrumb %}
{% block content %}
  <div class="col">
        {% if shipping_address %}
        <div class="h3">
            Recoger el pedido en el punto de entrega
        </div>
        <div class="">
            {% include "snippets/shipping_address.html" %}
            <div class="mt-2">
              <a href="{% url 'orders:confirm' %}" class="btn btn-warning">
                Entregar en esta direccion
              </a>
            </div>
            {% if can_choose_address %}
              <div class="mt-2">
                <a href="{% url 'orders:select_address' %}">Elige una direccion</a>
              </div>
            {% endif %}
        </div>
        {% else %}
        <div class="h3">
            Registra tu direccion de envio
        </div>
        <div class="">
            {% url 'orders:address' as next_url %}
            <a href="{% url 'shipping_address:create' %} ?next{{next_url}}">Nueva direccion de envio</a>
        </div>
        {% endif %}
  </div>
{% endblock content %}

orders/templates/confirm.html
{% extends "base/base.html" %}
{% block breadcrumb %}
    {% include "snippets/breadcrumb.html" %}
{% endblock breadcrumb %}
{% block content %}
    <div class="col-8">
        <div class="h3">
            Confirma tu pedido
        </div>
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-4">
                        <div class="font-weight-bold">
                            Direccion de Envio
                        </div>
                        <div class="cart-text">
                            {{shipping_address.address}}
                        </div>
                        <div class="cart-text">
                            {{shipping_address.line1}}
                        </div>
                        <div class="cart-text">
                            {{shipping_address.reference}}
                        </div>
                        <div class="cart-text">
                            {{shipping_address.postal_code}}
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="font-weight-bold">
                            Metodo de Pago
                        </div>
                        <div class="card-text">
                            Tarjeta Terminacion 4202
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="font-weight-bold">
                            Codigo Promocional
                        </div>
                        <form id="promocode-form" action="{% url 'promo_code:validar' %}">
                            <input type="text" name="code" value="{{order.promo_code.code}}" class="form-control" placeholder="Codigo Promocional" {% if order.promo_code %}readonly{% endif %}>
                        </form>
                        <div class="text-success" id="promocode-success" style="font-size:1em;">
                            {% if order.promo_code %}
                                Codigo aplicado exitosamente
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mt-3">
            <div class="card">
                <div class="card-body">
                    {% for product in cart.products.all %}
                      {% include "snippets/product.html" %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        {% url 'orders:complete' as next_url %}
        {% include "snippets/resume.html" with next_url=next_url %}
        <div class="mt-2">
            <a href="{% url 'orders:cancel' %}" class="btn btn-danger">Cancelar Orden</a>
        </div>
    </div>
{% endblock content %}

{% block javascript %}
    <script type="text/javascript">
        const form = document.getElementById('promocode-form')
        form.addEventListener('submit',function(e){
            e.preventDefault()
            const input = this.code
            const code = input.value
            const url = this.action+"?code="+code
            const div_total = document.getElementById('order-total')
            const div_success = document.getElementById('promocode-success')
            console.log(url)
            fetch(url)
                .then(response => response.json())
                .then(response => {
                    if(response.status === true){
                        div_total.innerHTML = "$" + response.total
                        div_success.classList.remove('text-danger')
                        div_success.classList.add('text-success')
                        div_success.innerHTML = 'Codigo aplicado de forma exitosa'

                        input.readOnly = true
                    }else{
                        div_success.innerHTML = 'Codigo no Valido'
                        div_success.classList.remove('text-success')
                        div_success.classList.add('text-danger')
                    }
                })
        })
    </script>
{% endblock javascript %}

orders/templates/order.html
{% extends 'base/base.html' %}
{% load product_extras %}
{% load carts_extras %}
{% block breadcrumb %}
    {% include "snippets/breadcrumb.html" %}
{% endblock breadcrumb %}
{% block content %}
    <div class="col-8">
        <div class="h3">
            Revista tu pedido
        </div>
        <div class="card">
            <div class="card-body">
                {% for product in cart.products.all %}
                  {% include "snippets/product.html" %}
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="col">
        {% url 'orders:address' as next_url %}
        {% include "snippets/resume.html" with next_url=next_url %}
    </div>
{% endblock content %}

orders/templates/orders.html
{% extends "base/base.html" %}
{% block content %}
  <div class="col">
      <div class="h3">
          Mis pedidos
      </div>
      <div class="">
          {% for order in object_list %}
            {% include "snippets/order.html" %}
          {% endfor %}
      </div>
  </div>
{% endblock content %}

orders/templates/select_address.html
{% extends "base/base.html" %}
{% block breadcrumb %}
  {% include "snippets/breadcrumb.html" %}
{% endblock breadcrumb %}
{% block content %}
  <div class="col">
      <div class="h3">
          Seleccione una direccion de envio
      </div>
      <div class="mt-2">
          {% for shipping_address in shipping_addresses %}
            <div class="card mb-2">
                <div class="card-body">
                    <div class="card-title">
                        <h5>
                            {{shipping_address.address}}
                        </h5>
                        <p class="cart-title">{{shipping_address.postal_code}}</p>
                        <a href="{% url 'orders:check_address' shipping_address.pk %}" class="btn btn-warning">Seleccionar direccion</a>
                    </div>
                </div>
            </div>
          {% endfor %}
      </div>
  </div>
{% endblock content %}