StoreOnline/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf.urls.static import static

from StoreOnline import views

urlpatterns = [
    path('usuarios/login',views.login_view, name='login'),
    path('usuarios/logout',views.logout_view, name='logout'),
    path('usuarios/register',views.register, name='register'),
    path('admin/', admin.site.urls),
    path('productos/', include('products.urls', namespace='products')),
    path('carrito/', include('carts.urls',namespace='carts')),
    path('ordenes/', include('orders.urls',namespace='orders')),
    path('direcciones/', include('shipping_address.urls', namespace='shipping_address')),
    path('codigos/', include('promo_code.urls', namespace='codes')),
    path('pagos/',include('billing_profiles.urls',namespace='billing_profiles')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

billing_profiles/urls.py
from django.urls import path
from billing_profiles import views

app_name = 'billing_profiles'

urlpatterns = [
    path('nuevo', views.create, name='create'),
]

carts/urls.py
from django.urls import path
from carts import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove'),
]

orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('direccion', views.address, name='address'),
    path('seleccionar/direccion', views.select_address, name='select_address'),
    path('establecer/direccion/<int:pk>', views.check_address, name='check_address'),
    path('confirmacion', views.confirm, name='confirm'),
    path('cancelar', views.cancel, name='cancel'),
    path('completar', views.complete, name='complete'),
    path('completados', views.OrderListView.as_view(), name='completed'),
]

products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='index'),
    path('search', views.ProductSearchView.as_view(), name='search'),
    path('<slug:slug>', views.ProductDetailView.as_view(), name='product'),
]

shipping_address/urls.py
from django.urls import path

from shipping_address import views

app_name = 'shipping_address'

urlpatterns = [
    path('', views.ShippingAddressListView.as_view(), name='shipping_addresses'),
    path('nueva', views.create, name='create'),
    path('editar/<int:pk>', views.ShippingAddressUpdateViews.as_view(), name='update'),
    path('eliminar/<int:pk>', views.ShippingAddressDeleteViews.as_view(), name='delete'),
    path('default/<int:pk>', views.default, name='default'),
]

templates/base/base.html
{% load static %}
{% load bootstrap4 %}

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% include 'base/navbar.html' %}
    <div class="container">
        {% include 'base/message.html' %}
        {% block breadcrumb %}
        {% endblock breadcrumb %}
        <div class="row mt-3">
            
            {% block content %}
            {% endblock content %}

        </div>
    </div>
</body>
<script src="{% static 'js/main.js' %}"></script>
<script src="https://kit.fontawesome.com/ed5652a487.js" crossorigin="anonymous"></script>
{% block javascript %}
  
{% endblock javascript %}
</html>

templates/base/message.html
{% load static %}
{% load bootstrap4 %}

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% if messages %}
            {% for message in messages %}
                <div class="alert {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %}">
                    <button type="button" class="close" data-dismiss="alert">X</button>
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}

templates/base/navbar.html
{% url 'login' as login %}
{% url 'register' as register %}
{% url 'carts:cart' as cart %}
{% url 'shipping_address:shipping_addresses' as shipping_addresses %}
{% url 'orders:completed' as completed %}
{% url 'billing_profiles:create' as billing_profiles%}

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <a href="{% url 'products:index' %}" class="navbar-brand">Store Online</a>
    <button type="button" name="button" class="navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#navb">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div id="navb" class="navbar-collapse hide">
        <ul class="navbar-nav">
            <li class="nav-item {% if request.path == cart %}active{% endif %}">
                <a class="nav-link" href="{{cart}}">
                Mi carrito <span class="fas fa-shopping-cart"></span>
                </a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item {% if request.path == shipping_addresses %}active{% endif %}">
                <a class="nav-link" href="{{shipping_addresses}}">
                Mis direcciones <span class="fas fa-location-arrow"></span>
                </a>
            </li>
            <li class="nav-item {% if request.path == completed %}active{% endif %}">
                <a class="nav-link" href="{{completed}}">
                Mis pedidos <span class="fas fa-shipping-fast"></span>
                </a>
            </li>
            <li class="nav-item {% if request.path == billing_profiles %}active{% endif %}">
                <a class="nav-link" href="{{billing_profiles}}">
                Mis metodos de pago <span class="fab fa-cc-stripe"></span>
                </a>
            </li>
            {% endif %}
        </ul>
        <ul class="nav navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="navbar-item">
                <a href="{% url 'logout' %}" class="nav-link"><span class="fas fa-sign-out-alt"></span>Logout</a>
            </li>
            {% else %}
            <li class="navbar-item {% if request.path == login %}active{% endif %}">
                <a href="{{login}}" class="nav-link"><span class="fas fa-user"></span>Login</a>
            </li>
            <li class="navbar-item {% if request.path == register %}active{% endif %}">
                <a href="{{register}}" class="nav-link"><span class="fas fa-sign-in-alt"></span>Registro</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>